// @vitest-environment node
// Run only against the isolated branch: DIGITAL_EXAM_INTEGRATION=1 bun test:run <this file>.
import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest'
import { randomUUID } from 'node:crypto'
import { PrismaClient, RoleTag } from '@prisma/client'
const identity = vi.hoisted(() => ({ id: '', tag: 'SERVANTS_PREP_STUDENT', readOnly: false }))
vi.mock('@/lib/auth-helpers', () => ({ requireAuth: async () => ({ id: identity.id }) }))
vi.mock('@/lib/authorization', () => ({ getAuthorizationContext: async () => ({ disabled: false, readOnly: identity.readOnly, roleTags: new Set([identity.tag]) }) }))
vi.mock('@/lib/exam-realtime', () => ({ publishExamChange: vi.fn(), examPusher: () => null }))
import { examScoreTransaction } from '@/lib/exam-score-service'
import { effectiveExamResult } from '@/lib/makeup-scores'
import { mutateExam } from '@/lib/digital-exam-service'
import { GET } from '@/app/api/digital-exams/[id]/route'
import { DELETE as deleteExam } from '@/app/api/exams/[id]/route'
import { GET as listExams } from '@/app/api/digital-exams/route'

const enabled = process.env.DIGITAL_EXAM_INTEGRATION === '1'
const db = new PrismaClient()
const fixture = { studentId: '', otherId: '', examId: '', yearId: '' }
const token = randomUUID()
const staff = { user: { id: 'test-proctor' }, staff: true, manage: true, student: false } as Parameters<typeof mutateExam>[2]
const student = () => ({ user: { id: fixture.studentId }, staff: false, manage: false, student: true }) as Parameters<typeof mutateExam>[2]
const act = (action: string, extra: Record<string, unknown> = {}) => mutateExam(fixture.examId, { action, sessionToken: token, ...extra }, student())
const admin = (action: string, extra: Record<string, unknown> = {}) => mutateExam(fixture.examId, { action, ...extra }, staff)
const get = () => GET(new Request('http://localhost'), { params: Promise.resolve({ id: fixture.examId }) })

describe.skipIf(!enabled)('digital exam database and API integration', () => {
  beforeAll(async () => {
    if (!process.env.DIGITAL_EXAM_TEST_DATABASE_URL || process.env.SP_DATABASE_URL !== process.env.DIGITAL_EXAM_TEST_DATABASE_URL) throw new Error('Set DIGITAL_EXAM_TEST_DATABASE_URL and SP_DATABASE_URL to the same isolated test branch URL.')
    const suffix = randomUUID()
    const year = await db.academicYear.create({ data: { name: `Digital exam test ${suffix}`, startDate: new Date('2026-01-01'), endDate: new Date('2027-01-01'), isActive: false } })
    fixture.yearId = year.id
    const users = await Promise.all(['student', 'other'].map(name => db.user.create({ data: { email: `digital-${name}-${suffix}@example.invalid`, name: `Digital test ${name}`, role: 'STUDENT', password: 'not-a-valid-hash', enrollments: { create: { academicYearId: year.id, yearLevel: 'YEAR_1' } }, roleAssignments: { create: { tag: RoleTag.SERVANTS_PREP_STUDENT, source: 'SYSTEM' } } } })))
    fixture.studentId = users[0].id; fixture.otherId = users[1].id; staff.user.id = users[1].id
    const section = await db.examSection.findFirstOrThrow()
    const exam = await db.exam.create({ data: { academicYearId: year.id, examSectionId: section.id, examDate: new Date(), yearLevel: 'YEAR_1', totalPoints: 100 } })
    fixture.examId = exam.id
  }, 30000)
  beforeEach(async () => {
    identity.id = fixture.studentId; identity.tag = 'SERVANTS_PREP_STUDENT'; identity.readOnly = false
    await db.digitalExamSheet.deleteMany({ where: { examId: fixture.examId } })
    await db.examScore.deleteMany({ where: { examId: fixture.examId } })
    await db.studentEnrollment.update({ where: { studentId: fixture.studentId }, data: { isActive: true, yearLevel: 'YEAR_1' } })
    const counts = Array(50).fill(4); counts[0] = 5; counts[7] = 8
    const key = Array(50).fill('A'); key[0] = 'E'; key[7] = 'H'
    await admin('configure', { choiceCounts: counts, answerKey: key }); await admin('open')
  }, 30000)
  afterAll(async () => {
    if (fixture.examId) await db.exam.delete({ where: { id: fixture.examId } })
    const ids = [fixture.studentId, fixture.otherId].filter(Boolean)
    if (ids.length) { await db.userRoleAssignment.deleteMany({ where: { userId: { in: ids } } }); await db.user.deleteMany({ where: { id: { in: ids } } }) }
    if (fixture.yearId) await db.academicYear.delete({ where: { id: fixture.yearId } })
    await db.$disconnect()
  }, 30000)
  it('saves mixed choices, hides keys and grades, publishes only on release', async () => {
    const start = await act('start')
    expect('attempt' in start).toBe(true)
    await act('save', { question: 0, answer: 'E', revision: 0 })
    await expect(act('save', { question: 1, answer: 'E', revision: 1 })).rejects.toThrow('valid answer')
    await act('submit', { revision: 1 })
    const response = await get(); const view = await response.json()
    expect(response.status).toBe(200)
    expect(view).not.toHaveProperty('answerKey')
    expect(view.sheet).not.toHaveProperty('answerKey')
    expect(view.attempt).not.toHaveProperty('correctCount')
    expect(await db.examScore.count({ where: { examId: fixture.examId } })).toBe(0)
    await admin('close'); await admin('release')
    const score = await db.examScore.findFirstOrThrow({ where: { examId: fixture.examId } })
    expect(score.percentage).toBe(2); expect(score.originalScore).toBe(2)
    expect((await get()).status).toBe(403)
    await admin('release')
    expect(await db.examScore.count({ where: { examId: fixture.examId } })).toBe(1)
  }, 30000)
  it('saves and grades an eighth choice without exposing the answer key', async () => {
    await act('start')
    await act('save', { question: 7, answer: 'H', revision: 0 })
    await act('submit', { revision: 1 })
    const view = await (await get()).json()
    expect(view.sheet.choiceCounts[7]).toBe(8)
    expect(view).not.toHaveProperty('answerKey')
    expect(view.attempt).not.toHaveProperty('correctCount')
    await admin('close'); await admin('release')
    expect((await db.examScore.findFirstOrThrow({ where: { examId: fixture.examId } })).percentage).toBe(2)
  }, 30000)
  it('shows student answer sheets only during proctoring, including direct links', async () => {
    const listed = async () => (await (await listExams()).json()).exams.some((e: { id: string }) => e.id === fixture.examId)
    expect(await listed()).toBe(true)
    expect((await get()).status).toBe(200)
    await act('start')
    await admin('close')
    expect(await listed()).toBe(false)
    expect((await get()).status).toBe(404)
    await admin('open')
    expect(await listed()).toBe(true)
    const view = await (await get()).json()
    expect(view.attempt.state).toBe('SUBMITTED')
    expect(view).not.toHaveProperty('answerKey')
    await admin('close'); await admin('release')
    expect(await listed()).toBe(false)
    expect((await get()).status).toBe(403)
  }, 30000)
  it('persists tab pause, deduplicates events, and only allows proctor unlock after return', async () => {
    await act('start')
    const event = { id: randomUUID(), kind: 'HIDDEN', at: new Date().toISOString() }
    await act('events', { events: [event], visible: false })
    const attempt = await db.digitalExamAttempt.findFirstOrThrow({ where: { examId: fixture.examId } })
    await expect(admin('unlock', { attemptId: attempt.id })).rejects.toThrow('return and reconnect')
    const blocked = await act('save', { question: 0, answer: 'E', revision: attempt.revision })
    expect(blocked).toHaveProperty('blocked', true)
    await act('events', { events: [{ id: randomUUID(), kind: 'RETURNED' }] })
    await admin('unlock', { attemptId: attempt.id })
    await act('events', { events: [event] })
    const resumed = await db.digitalExamAttempt.findUniqueOrThrow({ where: { id: attempt.id } })
    expect(resumed.state).toBe('ACTIVE')
    expect(await db.digitalExamEvent.count({ where: { attemptId: attempt.id, kind: 'HIDDEN' } })).toBe(1)
    await act('save', { question: 0, answer: 'E', revision: resumed.revision })
  }, 30000)
  it('records confirmed saves and clears without trusting forged activity or exposing history to students', async () => {
    await act('start')
    await act('save', { question: 11, answer: 'C', revision: 0 })
    await act('save', { question: 11, answer: '', revision: 1 })
    await act('save', { question: 11, answer: '', revision: 2 })
    const saved = await db.digitalExamEvent.findMany({ where: { attempt: { examId: fixture.examId }, kind: 'ANSWER_SAVED' }, orderBy: { createdAt: 'asc' } })
    expect(saved).toHaveLength(2)
    expect(saved.map(e => [e.questionNumber, e.answerChoice])).toEqual([[12, 'C'], [12, '']])
    expect((await (await get()).json()).attempt).not.toHaveProperty('events')
    await expect(act('events', { events: [{ id: randomUUID(), kind: 'ANSWER_SAVED', questionNumber: 1, answerChoice: 'A' }] })).rejects.toThrow('Invalid activity event')
    await act('events', { events: [{ id: randomUUID(), kind: 'BLUR' }] })
    const attempt = await db.digitalExamAttempt.findFirstOrThrow({ where: { examId: fixture.examId } })
    expect(await act('save', { question: 1, answer: 'A', revision: attempt.revision })).toHaveProperty('blocked', true)
    expect(await db.digitalExamEvent.count({ where: { attemptId: attempt.id, kind: 'ANSWER_SAVED' } })).toBe(2)
    identity.tag = 'SERVANTS_PREP_SERVANT'
    const view = await (await get()).json()
    const row = view.roster.find((r: { student: { id: string } }) => r.student.id === fixture.studentId)
    expect(row.attempt.pageVisible).toBe(true)
    expect(row.attempt.events.filter((e: { kind: string }) => e.kind === 'ANSWER_SAVED').map((e: { questionNumber: number; answerChoice: string }) => [e.questionNumber, e.answerChoice])).toEqual([[12, 'C'], [12, '']])
    expect(row.attempt.events.find((e: { kind: string }) => e.kind === 'ANSWER_SAVED')).not.toHaveProperty('answerKey')
  }, 30000)
  it('persists internal site navigation with a safe path and a mandatory pause', async () => {
    await act('start')
    await expect(act('events', { events: [{ id: randomUUID(), kind: 'SITE_NAVIGATION', destinationPath: 'https://other.example' }] })).rejects.toThrow('Invalid website destination')
    await act('events', { events: [{ id: randomUUID(), kind: 'SITE_NAVIGATION', destinationPath: '/dashboard/files?private=ignored' }] })
    const attempt = await db.digitalExamAttempt.findFirstOrThrow({ where: { examId: fixture.examId } })
    expect(attempt.state).toBe('PAUSED')
    const event = await db.digitalExamEvent.findFirstOrThrow({ where: { attemptId: attempt.id, kind: 'SITE_NAVIGATION' } })
    expect(event.destinationPath).toBe('/dashboard/files')
    identity.tag = 'SERVANTS_PREP_SERVANT'
    const view = await (await get()).json()
    expect(view.roster.find((r: { student: { id: string } }) => r.student.id === fixture.studentId).attempt.events.find((e: { kind: string }) => e.kind === 'SITE_NAVIGATION').destinationPath).toBe('/dashboard/files')
  }, 30000)
  it('persists focus-loss pauses on a visible page without auto-unlocking on focus return', async () => {
    await act('start')
    const event = { id: randomUUID(), kind: 'BLUR', at: new Date().toISOString() }
    await act('events', { events: [event], visible: true })
    let attempt = await db.digitalExamAttempt.findFirstOrThrow({ where: { examId: fixture.examId } })
    expect(attempt.state).toBe('PAUSED')
    expect(attempt.pageVisible).toBe(true)
    expect(await act('save', { question: 0, answer: 'E', revision: attempt.revision })).toHaveProperty('blocked', true)
    await act('events', { events: [{ id: randomUUID(), kind: 'FOCUS' }], visible: true })
    expect((await db.digitalExamAttempt.findUniqueOrThrow({ where: { id: attempt.id } })).state).toBe('PAUSED')
    await admin('unlock', { attemptId: attempt.id })
    await act('events', { events: [event] })
    attempt = await db.digitalExamAttempt.findUniqueOrThrow({ where: { id: attempt.id } })
    expect(attempt.state).toBe('ACTIVE')
    expect(await db.digitalExamEvent.count({ where: { attemptId: attempt.id, kind: 'BLUR' } })).toBe(1)
    await act('save', { question: 0, answer: 'E', revision: attempt.revision })
    identity.tag = 'SERVANTS_PREP_SERVANT'
    const view = await (await get()).json()
    expect(view.roster.find((row: { student: { id: string } }) => row.student.id === fixture.studentId).attempt.events.some((e: { kind: string }) => e.kind === 'BLUR')).toBe(true)
  }, 30000)
  it('detects stale contact and persists the pause even when an answer is blocked', async () => {
    await act('start')
    await db.digitalExamAttempt.updateMany({ where: { examId: fixture.examId }, data: { lastSeenAt: new Date(Date.now() - 31000) } })
    expect(await act('save', { question: 0, answer: 'E', revision: 0 })).toHaveProperty('blocked', true)
    const attempt = await db.digitalExamAttempt.findFirstOrThrow({ where: { examId: fixture.examId } })
    expect(attempt.state).toBe('PAUSED'); expect(attempt.answers[0]).toBe('')
    await act('heartbeat')
    await admin('unlock', { attemptId: attempt.id })
  }, 30000)
  it('rejects a competing session, then allows stale recovery only while paused', async () => {
    await act('start')
    const otherToken = randomUUID()
    await expect(act('start', { sessionToken: otherToken })).rejects.toThrow('another answering session')
    await db.digitalExamAttempt.updateMany({ where: { examId: fixture.examId }, data: { lastSeenAt: new Date(Date.now() - 31000) } })
    const recovered = await act('start', { sessionToken: otherToken })
    expect(recovered).toHaveProperty('attempt.state', 'PAUSED')
    await expect(act('heartbeat')).rejects.toThrow('owns this attempt')
  }, 30000)
  it('finalizes saved answers on close and cannot reopen a submitted attempt', async () => {
    await act('start'); await act('save', { question: 0, answer: 'E', revision: 0 })
    await admin('close'); await admin('open')
    expect(await act('start')).toHaveProperty('attempt.state', 'SUBMITTED')
    await expect(act('save', { question: 0, answer: 'A', revision: 2 })).rejects.toThrow('already been submitted')
    expect(await act('submit')).toHaveProperty('attempt.state', 'SUBMITTED')
  }, 30000)
  it('serializes concurrent close and save so no answer changes after finalization', async () => {
    await act('start')
    await Promise.allSettled([act('save', { question: 0, answer: 'E', revision: 0 }), admin('close')])
    const attempt = await db.digitalExamAttempt.findFirstOrThrow({ where: { examId: fixture.examId } })
    expect(attempt.state).toBe('SUBMITTED'); expect(attempt.correctCount).toBe(attempt.answers[0] === 'E' ? 1 : 0)
    await expect(act('save', { question: 0, answer: 'A', revision: attempt.revision })).rejects.toThrow('already been submitted')
  }, 30000)
  it('protects configuration, eligibility, read-only priests, and other attempts', async () => {
    await expect(admin('configure', { choiceCounts: Array(50).fill(4), answerKey: Array(50).fill('A') })).rejects.toThrow('locked after opening')
    await expect(mutateExam(fixture.examId, { action: 'close' }, { ...staff, manage: false })).rejects.toThrow('Forbidden')
    await db.studentEnrollment.update({ where: { studentId: fixture.studentId }, data: { yearLevel: 'YEAR_2' } })
    await expect(act('start')).rejects.toThrow('Forbidden')
    await db.studentEnrollment.update({ where: { studentId: fixture.studentId }, data: { yearLevel: 'YEAR_1', isActive: false } })
    expect((await get()).status).toBe(403)
    await db.studentEnrollment.update({ where: { studentId: fixture.studentId }, data: { isActive: true } })
    await act('start', { studentId: fixture.otherId })
    expect(await db.digitalExamAttempt.count({ where: { examId: fixture.examId, studentId: fixture.otherId } })).toBe(0)
    identity.tag = 'SUNDAY_SCHOOL_SERVANT'; expect((await get()).status).toBe(403)
  }, 30000)
  it('blocks an answer request reporting a hidden tab before saving it', async () => {
    await act('start')
    expect(await act('save', { question: 0, answer: 'E', revision: 0, visible: false })).toHaveProperty('blocked', true)
    const attempt = await db.digitalExamAttempt.findFirstOrThrow({ where: { examId: fixture.examId } })
    expect(attempt.state).toBe('PAUSED'); expect(attempt.answers[0]).toBe('')
  }, 30000)
  it('excludes already graded students, including zero scores, and preserves completed history', async () => {
    const grade = await db.examScore.create({ data: { examId: fixture.examId, studentId: fixture.studentId, score: 0, percentage: 0 } })
    expect((await (await listExams()).json()).exams.some((e: { id: string }) => e.id === fixture.examId)).toBe(false)
    expect((await get()).status).toBe(403)
    await expect(act('start')).rejects.toThrow('Forbidden')
    identity.tag = 'SERVANTS_PREP_SERVANT'
    const view = await (await get()).json()
    expect(view.roster.some((row: { student: { id: string } }) => row.student.id === fixture.studentId)).toBe(false)
    expect(view.roster.some((row: { student: { id: string } }) => row.student.id === fixture.otherId)).toBe(true)
    expect(await db.examScore.findUnique({ where: { id: grade.id } })).toEqual(grade)
    await db.examScore.delete({ where: { id: grade.id } })
    await act('start'); await act('submit', { revision: 0 }); await admin('close'); await admin('release')
    const completed = await (await get()).json()
    expect(completed.roster.some((row: { student: { id: string } }) => row.student.id === fixture.studentId)).toBe(false)
    expect(completed.hasAttempts).toBe(true)
    const history = completed.completedHistory.find((row: { student: { id: string } }) => row.student.id === fixture.studentId)
    expect(history.events.map((event: { kind: string }) => event.kind)).toContain('SUBMITTED')
  }, 30000)
  it('resets an empty test opening while preserving the key and every paper grade', async () => {
    await db.examScore.create({ data: { examId: fixture.examId, studentId: fixture.studentId, score: 90, percentage: 90 } })
    const grades = await db.examScore.findMany({ where: { examId: fixture.examId } })
    const before = await db.digitalExamSheet.findUniqueOrThrow({ where: { examId: fixture.examId } })
    await admin('reset')
    const after = await db.digitalExamSheet.findUniqueOrThrow({ where: { examId: fixture.examId } })
    expect(after.state).toBe('DRAFT'); expect(after.openedAt).toBeNull(); expect(after.closedAt).toBeNull()
    expect(after.answerKey).toEqual(before.answerKey); expect(after.choiceCounts).toEqual(before.choiceCounts)
    expect(await db.examScore.findMany({ where: { examId: fixture.examId } })).toEqual(grades)
    expect((await get()).status).toBe(403)
    await admin('configure', { choiceCounts: before.choiceCounts, answerKey: before.answerKey })
    await admin('open')
    expect((await get()).status).toBe(403)
  }, 30000)
  it('blocks resets after a student joins and for priests or students', async () => {
    await expect(act('reset')).rejects.toThrow('Forbidden')
    await expect(mutateExam(fixture.examId, { action: 'reset' }, { ...staff, manage: false })).rejects.toThrow('Forbidden')
    await act('start')
    await expect(admin('reset')).rejects.toThrow('student has joined')
    await act('submit', { revision: 0 }); await admin('close')
    await expect(admin('reset')).rejects.toThrow('student has joined')
    await admin('release')
    await expect(admin('reset')).rejects.toThrow('Released exams')
  }, 30000)
  it('serializes starting and resetting so a joined attempt is never erased', async () => {
    await Promise.allSettled([act('start'), admin('reset')])
    const sheet = await db.digitalExamSheet.findUniqueOrThrow({ where: { examId: fixture.examId } })
    const attempts = await db.digitalExamAttempt.count({ where: { examId: fixture.examId } })
    expect(sheet.state === 'OPEN' ? attempts === 1 : sheet.state === 'DRAFT' && attempts === 0).toBe(true)
  }, 30000)
  it('protects saved scores and digital attempts against full exam deletion', async () => {
    const remove = () => deleteExam(new Request('http://localhost', { method: 'DELETE' }), { params: Promise.resolve({ id: fixture.examId }) })
    expect((await remove()).status).toBe(403)
    identity.tag = 'PRIEST'; identity.readOnly = true
    expect((await remove()).status).toBe(403)
    identity.tag = 'SERVANTS_PREP_SERVANT'; identity.readOnly = false
    await db.examScore.create({ data: { examId: fixture.examId, studentId: fixture.studentId, score: 90, percentage: 90 } })
    const grade = await db.examScore.findFirstOrThrow({ where: { examId: fixture.examId } })
    expect((await remove()).status).toBe(409)
    expect(await db.examScore.findUnique({ where: { id: grade.id } })).toEqual(grade)
    await db.examScore.delete({ where: { id: grade.id } })
    await act('start')
    expect((await remove()).status).toBe(409)
    expect(await db.digitalExamAttempt.count({ where: { examId: fixture.examId } })).toBe(1)
  }, 30000)
  it('allows deleting an empty test exam', async () => {
    const source = await db.exam.findUniqueOrThrow({ where: { id: fixture.examId } })
    const empty = await db.exam.create({ data: { academicYearId: source.academicYearId, examSectionId: source.examSectionId, examDate: new Date(), yearLevel: 'YEAR_1', totalPoints: 100 } })
    try {
      identity.tag = 'SERVANTS_PREP_SERVANT'
      const response = await deleteExam(new Request('http://localhost', { method: 'DELETE' }), { params: Promise.resolve({ id: empty.id }) })
      expect(response.status).toBe(200)
      expect(await db.exam.findUnique({ where: { id: empty.id } })).toBeNull()
    } finally { await db.exam.deleteMany({ where: { id: empty.id } }) }
  }, 30000)
  it('does not overwrite existing paper grades when releasing results', async () => {
    await act('start'); await act('submit', { revision: 0 }); await admin('close')
    await db.examScore.create({ data: { examId: fixture.examId, studentId: fixture.studentId, score: 90, percentage: 90 } })
    await expect(admin('release')).rejects.toThrow('Existing grades overlap')
    expect((await db.digitalExamSheet.findUniqueOrThrow({ where: { examId: fixture.examId } })).releasedAt).toBeNull()
    expect((await db.examScore.findFirstOrThrow({ where: { examId: fixture.examId } })).percentage).toBe(90)
  }, 30000)
  it('approves individual retakes, archives submissions, withholds results and keeps the highest score', async () => {
    await act('start'); await act('save', { question: 0, answer: 'E', revision: 0 }); await act('submit', { revision: 1 })
    await admin('close'); await admin('release')
    const first = await db.digitalExamAttempt.findFirstOrThrow({ where: { examId: fixture.examId } })
    const oldGrade = await db.examScore.findFirstOrThrow({ where: { examId: fixture.examId } })
    await expect(act('retake', { studentId: fixture.studentId })).rejects.toThrow('Forbidden')
    await expect(mutateExam(fixture.examId, { action: 'retake', studentId: fixture.studentId }, { ...staff, manage: false })).rejects.toThrow('Forbidden')
    await expect(admin('open')).rejects.toThrow('approved individual retake')
    await admin('retake', { studentId: fixture.studentId }); await admin('retake', { studentId: fixture.studentId })
    expect(await db.digitalExamAttemptArchive.count({ where: { attemptId: first.id } })).toBe(1)
    const archive = await db.digitalExamAttemptArchive.findFirstOrThrow({ where: { attemptId: first.id } })
    expect(archive.snapshot).toMatchObject({ answers: first.answers, correctCount: 1, submittedAt: first.submittedAt!.toISOString() })
    expect(await db.examScore.findUnique({ where: { id: oldGrade.id } })).toEqual(oldGrade)
    await admin('open')
    expect((await (await listExams()).json()).exams.some((e: { id: string }) => e.id === fixture.examId)).toBe(true)
    identity.id = fixture.otherId
    expect((await get()).status).toBe(404)
    expect((await (await listExams()).json()).exams.some((e: { id: string }) => e.id === fixture.examId)).toBe(false)
    identity.id = fixture.studentId
    const start = await act('start', { sessionToken: randomUUID() })
    expect(start).toHaveProperty('attempt.attemptNumber', 2)
    const next = await db.digitalExamAttempt.findUniqueOrThrow({ where: { id: first.id } })
    expect(next.answers.every(a => a === '')).toBe(true)
    await expect(act('heartbeat')).rejects.toThrow('owns this attempt')
    await expect(admin('retake', { studentId: fixture.studentId })).rejects.toThrow('current attempt')
    const newToken = randomUUID()
    await db.digitalExamAttempt.update({ where: { id: first.id }, data: { lastSeenAt: new Date(Date.now() - 31000) } })
    await act('start', { sessionToken: newToken }); await admin('unlock', { attemptId: first.id })
    let revision = (await db.digitalExamAttempt.findUniqueOrThrow({ where: { id: first.id } })).revision
    await act('save', { sessionToken: newToken, question: 0, answer: 'E', revision: revision++ })
    await act('save', { sessionToken: newToken, question: 1, answer: 'A', revision: revision++ })
    await act('submit', { sessionToken: newToken, revision })
    expect((await (await get()).json()).attempt).not.toHaveProperty('correctCount')
    expect(await db.examScore.findUnique({ where: { id: oldGrade.id } })).toEqual(oldGrade)
    await admin('close'); await admin('release'); await admin('release')
    const improved = await db.examScore.findUniqueOrThrow({ where: { id: oldGrade.id } })
    expect(improved.percentage).toBe(4); expect(improved.originalPercentage).toBe(2)
    await admin('retake', { studentId: fixture.studentId }); await admin('open')
    const last = await act('start')
    expect(last).toHaveProperty('attempt.attemptNumber', 3)
    await act('submit', { revision: (await db.digitalExamAttempt.findUniqueOrThrow({ where: { id: first.id } })).revision })
    await admin('close'); await admin('release')
    expect(await db.examScore.findUnique({ where: { id: oldGrade.id } })).toEqual(improved)
    expect(await db.digitalExamAttemptArchive.count({ where: { attemptId: first.id } })).toBe(2)
    expect(await db.digitalExamEvent.count({ where: { attemptId: first.id, attemptNumber: 1, kind: 'SUBMITTED' } })).toBe(1)
  }, 60000)
  it('allows an existing paper score retake without reducing or changing paper makeup records', async () => {
    const grade = await db.examScore.create({ data: { examId: fixture.examId, studentId: fixture.studentId, score: 90, percentage: 90, originalScore: 80, originalPercentage: 80 } })
    const makeup = await db.makeupExamScore.create({ data: { examScoreId: grade.id, version: 1, score: 90, percentage: 90, totalPoints: 100, takenDate: new Date() } })
    await admin('retake', { studentId: fixture.studentId })
    await admin('close')
    expect((await db.digitalExamAttempt.findFirstOrThrow({ where: { examId: fixture.examId } })).retakeReady).toBe(true)
    await admin('open')
    const start = await act('start')
    expect(start).toHaveProperty('attempt.attemptNumber', 2)
    await act('submit', { revision: 1 }); await admin('close'); await admin('release')
    expect(await db.examScore.findUnique({ where: { id: grade.id } })).toMatchObject({ score: 90, percentage: 90, originalScore: 80, originalPercentage: 80, digitalRetakePercentage: 0 })
    expect(await db.makeupExamScore.findUnique({ where: { id: makeup.id } })).toEqual(makeup)
  }, 30000)

  it('sets completed exams ready to open without clearing grades, keys or individual approvals', async () => {
    await act('start')
    await expect(admin('ready')).rejects.toThrow('Close the exam')
    await expect(act('ready')).rejects.toThrow('Forbidden')
    await admin('close'); await admin('release')
    const grade = await db.examScore.findFirstOrThrow({ where: { examId: fixture.examId } })
    const sheet = await db.digitalExamSheet.findUniqueOrThrow({ where: { examId: fixture.examId } })
    await admin('retake', { studentId: fixture.studentId }); await admin('ready')
    expect(await db.digitalExamSheet.findUnique({ where: { examId: fixture.examId } })).toMatchObject({ state: 'DRAFT', openedAt: sheet.openedAt, answerKey: sheet.answerKey, releasedAt: sheet.releasedAt })
    expect((await get()).status).toBe(404)
    expect(await db.examScore.findUnique({ where: { id: grade.id } })).toEqual(grade)
    await admin('open')
    expect(await act('start')).toHaveProperty('attempt.attemptNumber', 2)
  }, 30000)

  it('preserves the highest grade when a retake release races with a paper grade correction', async () => {
    await db.examScore.create({ data: { examId: fixture.examId, studentId: fixture.studentId, score: 0, percentage: 0, originalScore: 0, originalPercentage: 0 } })
    await admin('retake', { studentId: fixture.studentId }); await act('start')
    await act('save', { question: 0, answer: 'E', revision: 1 }); await act('submit', { revision: 2 }); await admin('close')
    await Promise.all([admin('release'), examScoreTransaction(async tx => {
      const record = await tx.examScore.findUniqueOrThrow({ where: { examId_studentId: { examId: fixture.examId, studentId: fixture.studentId } } })
      await tx.examScore.update({ where: { id: record.id }, data: { originalScore: 90, originalPercentage: 90, ...effectiveExamResult(90, [], 100, record.digitalRetakePercentage) } })
    })])
    expect(await db.examScore.findFirstOrThrow({ where: { examId: fixture.examId } })).toMatchObject({ percentage: 90, originalPercentage: 90, digitalRetakePercentage: 2 })
  }, 30000)

  it('lets only Servants Prep servants toggle student return sounds without changing answers or grades', async () => {
    expect((await (await get()).json()).sheet.studentReturnSoundEnabled).toBe(false)
    await act('start'); await act('save', { question: 0, answer: 'E', revision: 0 })
    const attempt = await db.digitalExamAttempt.findFirstOrThrow({ where: { examId: fixture.examId } })
    const grades = await db.examScore.findMany({ where: { examId: fixture.examId } })
    await expect(act('studentSound', { enabled: true })).rejects.toThrow('Forbidden')
    await expect(mutateExam(fixture.examId, { action: 'studentSound', enabled: true }, { ...staff, manage: false })).rejects.toThrow('Forbidden')
    await expect(admin('studentSound', { enabled: 'true' })).rejects.toThrow('Choose whether')
    await admin('studentSound', { enabled: true })
    expect((await (await get()).json()).sheet.studentReturnSoundEnabled).toBe(true)
    await admin('studentSound', { enabled: false })
    expect((await (await get()).json()).sheet.studentReturnSoundEnabled).toBe(false)
    expect(await db.digitalExamAttempt.findUnique({ where: { id: attempt.id } })).toEqual(attempt)
    expect(await db.examScore.findMany({ where: { examId: fixture.examId } })).toEqual(grades)
  }, 30000)

})
