const { withAppDelegate } = require("@expo/config-plugins");

const WINDOW_BLOCK =
  '#if os(iOS) || os(tvOS)\n' +
  '    window = UIWindow(frame: UIScreen.main.bounds)\n' +
  '    factory.startReactNative(\n' +
  '      withModuleName: "main",\n' +
  '      in: window,\n' +
  '      launchOptions: launchOptions)\n' +
  '#endif\n\n';

const OLD_CLASS_DECL = "class AppDelegate: ExpoAppDelegate {";
const NEW_CLASS_DECL =
  "class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {";

/**
 * iOS 27 asserts at launch unless the app adopts the scene-based life cycle
 * (UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption), which this
 * project's default Expo-generated AppDelegate never did. Expo SDK 57 ships
 * a ready-made scene delegate (expo/ios/AppDelegates/ExpoAppSceneDelegate.swift,
 * ObjC name EXExpoAppSceneDelegate, wired in via the UIApplicationSceneManifest
 * in app.json's ios.infoPlist) — this plugin makes AppDelegate hand off window
 * creation to it instead of creating the window itself, which is the other half
 * of that adoption. `ios/` is regenerated by `expo prebuild` and isn't committed,
 * so this has to be a config plugin, not a one-off hand edit.
 */
function withSceneDelegate(config) {
  return withAppDelegate(config, (config) => {
    let contents = config.modResults.contents;

    if (contents.includes(OLD_CLASS_DECL)) {
      contents = contents.replace(OLD_CLASS_DECL, NEW_CLASS_DECL);
    }

    if (contents.includes(WINDOW_BLOCK)) {
      contents = contents.replace(WINDOW_BLOCK, "");
    }

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withSceneDelegate;
